# Generated by Django 4.2.19 on 2025-02-27 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name must be at least 2 characters', regex='^[a-zA-Z-]{2,}$'), django.core.validators.RegexValidator(message='Name can only contain uppercase letters, lowercase letters, and hyphens', regex='^[a-zA-Z-]+$')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
