# Generated by Django 4.2.19 on 2025-02-27 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name must be at least 2 characters can only contain uppercase letters, lowercase letters, and hyphens', regex='^[a-zA-Z-]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone number must be in one of the following forms: (XXX) XXX-XXXX, X-XXX-XXX-XXXX, XXX-XXX-XXXX, XXX.XXX.XXXX', regex='^(\\(\\d{3}\\)\\s?\\d{3}-\\d{4}|\\d{1}-\\d{3}-\\d{3}-\\d{4}|\\d{3}-\\d{3}-\\d{4}|\\d{3}\\.\\d{3}\\.\\d{4})$')]),
        ),
    ]
